################################################################################
#   GLOBAL
################################################################################
email: "benoit.guibert@free.fr"
nb_threads: 12

genome:
    # ""
    # "/data/genomes/GRCh37/GRCh37.fa"
    "/data/genomes/GRCh38/GRCh38.fa"

bed_file:
    "../manifest.bed"

gtf_ref:
    # "/data/annotations/human/ensembl.gff"
    "/data/annotations/human/Homo_sapiens.GRCh38.86.gtf"


version_dir: 'logs/versions'

################################################################################
#   MAPPING
################################################################################

crac:
    binary: "crac"
    index: "/data/indexes/crac/GRCh38/GRCh38"
    kmer_len: "22"
    output_dir: 'mapping/crac'
    summary_dir: 'reports/crac/summary'
    log_dir: 'logs/crac'
    options: "--nb-tags-info-stored 10000 --stranded --detailed-sam"
        # some options : --bam --nb-tags-info-stored 1000 --stranded  --detailed-sam

bwa:
    binary: "bwa"
    output_dir: "mapping/bwa"
    log_dir: ""
    options: ""
    index: "/data/indexes/bwa/GRCh37/GRCh37.fa"

hisat2:
    binary: "hisat2"
    output_dir: "mapping/hisat2"
    log_dir: "logs/hisat2"
    options: ""
    index: "/data/indexes/hisat2/GRCh38-hisat2/GRCh38"
        # /data/indexes/hisat2/GRCh38-hisat2/

samtools:
    mem: '2G'
    threads: '4'

################################################################################
#   READS ANALYSIS
################################################################################

cractools:
    binary: "cractools"
    output_dir:
        chimeras:   "cractools/chimeras"
        splices:    "cractools/splices"
        mutations:  "cractools/mutations"
    log_dir:        "logs/cractools"
    nb_threads:     4
    options:        "--coverless-splices"      
                    # --coverless-splices --stranded

extract_common_chimeras:
    binary:         "extractCommonChimeras.pl"
    output_dir:     "extract_common_chimeras"
    log_file:       "logs/extract_common_chimeras.log"
    # option_genome:  True
    options:        ""

################################################################################
#   VARIANT CALLING
################################################################################

freebayes:
    binary: "freebayes"
    output_dir: "mutations/freebayes"
    bed:        "../manifest.bed"
    log_dir:    "logs/freebayes"
    options:    "" 
                # "-C 10 -F 0.008"

################################################################################
#   ANNOTATION & CLASSIFICATION
################################################################################

chimct:
    binary:             "chimCT"
    output_dir:         "chimct"
    output_suffix:      "_chimct.tsv"
    log_dir:            "logs/chimct"
    gff:                "/data/annotations/human/ensembl.gff"
    tmp_dir:            "/tmp"
    gsnap_binary:       "gsnap"
    gsnap_genome_name:  "GRCh38"
    gsnap_genome_dir:   "/data/indexes/gsnap/GRCh38"
    #gsnap_threads:      12
    summary_dir:       "reports/chimct"
    #option_rename:  'stranded'
    options:            "--verify-splice --detailed-sam  --stranded"
                        #--verify-splice --detailed-sam --stranded --keep-ig --est 

################################################################################
#   RNA RECONSTRUCTION
################################################################################

stringtie:
    binary:         'stringtie'
    output_dir:     'reconstruction/stringtie'
    output_merge:   'unannotated_lncRNA_primarymerge.gtf'
    log_dir:        'logs/stringtie'
    nb_threads:     '4'
    min_length:     '200'
    min_iso:        '0.2'

################################################################################
#   RNA ANNOTATION
################################################################################

bedtools:
    binary:             'bedtools'
    log_dir:            'logs/bedtools'
    # subtrack
    output_subtrack:    'annotation/unannotated_lincRNA_minusgenes.gtf'
    subtract_options:   '-A'
    # intersect
    output_intersect:   'annotation/unannotated_lincRNA_intersect.gtf'
    intersect_options:  '-wa -u -S'

gtf_exon_remove:
    binary:             'perl /data/bin/gtf_exon_remove.pl'
    output_file:        'annotation/unannotated_lincRNA_v2.gtf'
    log_file:           'logs/gtf_exon_remove.err'
    options:            ''

gffread:
    binary:             'gffread'
    output_file:        'annotation/unannotated_lincRNA_v2.fa'
    log_file:           'logs/gffread.err'
    options:            ''

################################################################################
#   ABUNDANCE
################################################################################

kallisto:
    binary: ""
    index:  "/data/indexes/kallisto/GRCh38.idx"
    output_dir: "output/kallisto"
    log_dir: ""
    options: ""

