################################################################################
#   GLOBAL
################################################################################

reads_dir: "fastq"
    # "/data/nas/internal/2012/GATC/RNA-Seq-LAM"


fastx_suffix: ""

genome:
    # ""
    # "/data/genomes/GRCh37/GRCh37.fa"
    "/data/genomes/GRCh38/GRCh38.fa"

annotation_file: "/data/annotations/human/ensembl.gff"
    # "/data/annotations/human/Homo_sapiens.GRCh38.83.gtf"

report_versions: "reports/tool_versions.txt"
nb_threads: 12
email: "benoit.guibert@free.fr"

################################################################################
#   MAPPING
################################################################################

crac:
    index: "/data/indexes/crac/GRCh38/GRCh38"
    kmer_len: "22"
    output_dir: "mapping/crac"
    summary_dir: "reports/crac/summary"
    log_dir: "logs/crac"
    options: "--bam --nb-tags-info-stored 10000 --stranded"
        # some options : --bam --nb-tags-info-stored 1000 --stranded

bwa:
    output_dir: "mapping/bwa"
    log_dir: ""
    options: ""
    nb_threads: ""
    index: "/data/indexes/bwa/GRCh37/GRCh37.fa"

hisat2:
    output_dir: "mapping/hisat2"
    log_dir: "logs/hisat2"
    options: ""
    nb_threads: "16"
    index: "/data/indexes/hisat2/GRCh38_with_MT"
        # /data/indexes/hisat2/GRCh38-hisat2/


################################################################################
#   READS ANALYSIS
################################################################################

cractools:
    output_dir:
        chimeras:   "chimeras/cractools"
        splices:    "splices/cractools"
        mutations:  "mutations/cractools"
    log_dir:        "logs/cractools"
    options:        "--coverless-splices"      # --coverless-splices --stranded

extract_common_chimeras:
    output_dir: "chimeras/common_chimeras"
    log_file:   "logs/extract_common_chimeras.log"
    options:    ""

################################################################################
#   VARIANT CALLING
################################################################################

freebayes:
    output_dir: "mutations/freebayes"
    bed:        "../manifest.bed"
    log_dir:    "logs/freebayes"
    options:    "" 
                # "-C 10 -F 0.008"

################################################################################
#   ANNOTATION & CLASSIFICATION
################################################################################

chimct:
    binary:         "/data/bin/chimCT"
    output_dir:     "chimeras/chimct"
    output_suffix:  "_chimct.tsv"
    log_dir:        "logs/chimct"
    log_suffix:     "_chimct.log"
    options:        "--verify-splice --detailed-sam  --stranded"
                    #--verify-splice --detailed-sam --stranded --keep-ig --est 
    gff:            "/data/annotations/human/ensembl.gff"
    nb_threads:     "12"
    tmp_dir:        ""
    gsnap_genome_name: "GRCh38"
    gsnap_genome_dir: "/data/indexes/gsnap/GRCh38"
    gsnap_binary: "/data/bin/gsnap"


################################################################################
#   ABUNDANCE
################################################################################

kallisto:
    binary: ""
    index:  "/data/indexes/kallisto/GRCh38.idx"
    output_dir: "output/kallisto"
    log_dir: ""
    options: ""

