annotation_file: /data/annotations/human/ensembl.gff
bwa:
  binary: ''
  index: /data/indexes/bwa/GRCh37/GRCh37.fa
  log_dir: ''
  nb_threads: ''
  options: ''
  output_dir: output/bwa
chimct:
  binary: /data/bin/chimCT
  gff: /data/annotations/human/ensembl.gff
  gsnap_binary: /data/bin/gsnap
  gsnap_genome_dir: /data/indexes/gsnap/GRCh38
  gsnap_genome_name: GRCh38
  log_dir: logs/chimct
  log_suffix: _chimct.log
  nb_threads: '12'
  options: --verify-splice --detailed-sam  --stranded
  output_dir: output/chimct
  output_suffix: _chimct.tsv
  tmp_dir: ''
crac:
  binary: /data/bin/crac
  index: /data/indexes/crac/GRCh38/GRCh38
  kmer_len: '22'
  log_dir: logs/crac
  options: --bam --nb-tags-info-stored 10000 --stranded
  output_dir: output/crac
  summary_dir: reports/crac/summary
cractools:
  binary: /data/bin/cractools
  log_dir: logs/cractools
  options: --coverless-splices
  output_dir:
    chimeras: output/cractools/chimeras
    mutations: output/cractools/mutations
    splices: output/cractools/splices
email: benoit.guibert@free.fr
extract_common_chimeras:
  binary: /data/bin/extractCommonChimeras.pl
  log_file: logs/extract_common_chimeras.log
  options: ''
  output_dir: output/common_chimeras
  version: ''
fastx_suffix: ''
freebayes:
  binary: ''
  log_dir: logs/freebayes/
  options: ''
  output_dir: ''
  version: ''
genome: ''
hisat2:
  binary: usr/bin/hisat2
  index: /data/indexes/hisat2/GRCh38_with_MT
  log_dir: logs/hisat2
  nb_threads: '16'
  options: ''
  output_dir: output/hisat2
kallisto:
  binary: ''
  index: /data/indexes/kallisto/GRCh38.idx
  log_dir: ''
  options: ''
  output_dir: output/kallisto
  version: ''
nb_threads: 15
reads_dir: tmp
report_versions: reports/tool_versions.txt
samples:
  paired:
    17U_: .fastq.gz
    17W_: .fastq.gz
    17X_: .fastq.gz
    17Y_: .fastq.gz
    17Z_: .fastq.gz
    '180_': .fastq.gz
    '182_': .fastq.gz
    '183_': .fastq.gz
    '186_': .fastq.gz
    '187_': .fastq.gz
    18A_: .fastq.gz
    18B_: .fastq.gz
    18C_: .fastq.gz
    18D_: .fastq.gz
    '246_': .fastq.gz
    '247_': .fastq.gz
  rejected: {}
  unpaired: {}
